Drop TABLE IF EXISTS USERS;

CREATE TABLE USERS(
    USERID      VARCHAR(12)     NOT NULL,
    PASSWORD    VARCHAR(12)     NOT NULL,
    NAME        VARCHAR(20)     NOT NULL,
    EMAIL       VARCHAR(50),

    PRIMARY KEY     (USERID)
);